### ISSUE TITLE
why tho

### ISSUE THREAD

**Issue by dev-gm** [ErisBlastar/cplusequality#41]
why did you feel the need to make this

**Comment by BenMcLean** [comment]
> why did you feel the need to make this

Because feminism is brain cancer.

**Comment by dev-gm** [comment]
Bro stop being an incel and touch some grass. Real feminism, not that Buzfeed misandrist radlib shit, advocates for equality between men and women. Not that long ago women had to have their husbands' permission to do anything, marital rape was totally legal, and you weren't able to get a divorce, even if your spouse was an abuser. Not even a century ago women couldn't vote, own property, or freely express themselves. Feminism stopped all that. Just because now you can't get a fucking girlfriend because women actually have freedom in who and whether they marry doesn't mean feminism is bad, it just means that people don't want to be in a relationship with you. Just because divorce rates have risen exponentially doesn't mean feminism is bad, it means that now that women are more freely allowed to divorce, they have decided to leave their domestic abusers. A gender pay gap does exist. Although it isn't as high as some claim it is, there is still a nearly 6 cent per dollar difference between men and women's pay, fully taking into consideration different job choices and such. Most women have experienced sexual harassment. Many (1 in 5) have experienced sexual assault. Stop watching whatever cherrypicking anti-SJW crap and embrace reality.

**Comment by BenMcLean** [comment]
> Real feminism, not that Buzfeed misandrist radlib shit, advocates for equality between men and women.

And real feminism, as so defined, is still brain cancer. I don't want absolute equality between men and women. I want a male-only draft. I want the traditional rule of women-and-children-first in emergencies. I want boys raised to believe that it's their responsibility as a man to protect women and children as a matter of honor. I don't want 50% of garbage truck drivers, sanitation workers and minimum wage day laborers to be female. And I want every single Western feminist to go to the Middle East where there are real abuses of women and make changes there, leaving the West alone.

Do you seriously think that 20th and 21st century politicians like Richard Nixon and Bill Clinton elected with women voting were superior to 18th and 19th century politicians like George Washington and Abraham Lincoln elected without women voting?

**Comment by activedecay** [comment]
Ben spittin fax but dev-gm can't hear him over the ree.

This is a joke code base, so try and lol a bit.

Does github administrate argumentative threads? Ree hard enough dev-gm and you'll get this code memory-holed like you want.

**Comment by socram8888** [comment]
We need to have this issue locked. Facts hurt my feelings and can't have that in this Safe Space that is ~~Tum~~GitHub.

**Comment by boehs** [comment]
> I don't want. I want. I want. I want. I don't want. And I want.

Ben, it's not always about what you want.

**Comment by BenMcLean** [comment]
> Ben, it's not always about what you want.

That's a valid point. I should have phrased all of that in terms of objective morality, because it totally is, instead of as subjective preference.

**Comment by dev-gm** [comment]
> > Ben, it's not always about what you want.
> 
> That's a valid point. I should have phrased all of that in terms of objective morality, because it totally is, instead of as subjective preference.

I don't know if you are a men's rights activist or mra-adjacent, but it really isn't helping the disproportionately high male suicide rate to claim that it is objectively moral for all the dangerous and disgusting jobs, even if they don't require the extra strength that men on average have, to only be preformed by men.

**Comment by BenMcLean** [comment]
> I don't know if you are a men's rights activist or mra-adjacent

I'm not an MRA. I'm a Christian moral traditionalist complementarian.

Feminism is brain cancer. MRA is just brain cancer for men.

> it is objectively moral for all the dangerous and disgusting jobs, even if they don't require the extra strength that men on average have, to only be preformed by men.

I did not say that. Just saying there's no moral obligation to force these jobs into being 50% women. Some jobs are gonna have more men than women in them or vice versa and that's fine.

**Comment by TPS** [comment]
> the disproportionately high male suicide rate

How do you assume ~~radical~~ revolutionary feminism has a _solution_ for this?

**Comment by dev-gm** [comment]
> > the disproportionately high male suicide rate
> 
> How do you assume ~~radical~~ revolutionary feminism has a _solution_ for this?

By redefining gender roles and expectations so that men are not forced to hide their emotions and not open up. By making dangerous jobs not mainly done by men. Every argument that mra activists bring up are addressed and solved by feminism. Equality goes both ways.

**Comment by BenMcLean** [comment]
> By redefining gender roles and expectations so that men are not forced to hide their emotions and not open up.

This isn't something most men are looking for.

> By making dangerous jobs not mainly done by men.

I don't think danger causes suicide.

> Equality goes both ways.

Absolute equality between men and women would be bad for both.

**Comment by dev-gm** [comment]
> > By redefining gender roles and expectations so that men are not forced to hide their emotions and not open up.
> 
> This isn't something most men are looking for.
> 
> > By making dangerous jobs not mainly done by men.
> 
> I don't think danger causes suicide.
> 
> > Equality goes both ways.
> 
> Absolute equality between men and women would be bad for both.

You don't think that having to suppress their emotions for their entire life doesn't have an impact on mental health? You don't think that being expected to be shipped off to war impacts mental health?
What fundamental differences do you think, other than physical strength, are there between men and women that would make equality bad for both?

**Comment by fche** [comment]
> What fundamental differences do you think, other than physical strength, are there between men and women that would make equality bad for both?

Define "equality".

**Comment by BenMcLean** [comment]
> You don't think that having to suppress their emotions for their entire life doesn't have an impact on mental health?

That is generally something men naturally do, not something society is making them do.

> You don't think that being expected to be shipped off to war impacts mental health?

Who in the United States and Europe actually expects that?

> What fundamental differences do you think, other than physical strength, are there between men and women that would make equality bad for both?

First of all, a ***forced*** equality is just a bad thing in general. Like the song says, "The trees are all kept equal by hatchet, axe and saw."

Second, men and women think differently. They value different things in life. This leads them to make different choices. Different choices have different outcomes. Then feminists come along and make the claim that the different outcomes are the result of a vast, evil conspiracy against women which pervades all of society. There just isn't one.

**Comment by boehs** [comment]
> That is generally something men naturally do, not something society is making them do.

To support the idea that men's emotional suppression is cultural, I found a study [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5381435/) that finds emotion is influenced by culture, and it is undeniably true that our culture paints men as less emotional.

I found the following to complement my hypothesis that men hide emotion due to culture:

* https://www.researchgate.net/publication/23547227_Gender_Differences_in_Responses_to_Emotional_Advertising_A_Social_Desirability_Perspective
* and https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0158666#sec013

Still not conclusive, but without any citation for your claims I am inclined to trust my research based hypothesis. That being said, I would love to hear your source for "men suppressing their emotions naturally", as I am sure I was biased in my research.

---

> Second, men and women think differently. They value different things in life. This leads them to make different choices. Different choices have different outcomes. Then feminists come along and make the claim that the different outcomes are the result of a vast, evil conspiracy against women which pervades all of society. There just isn't one.

>> Men and woman think differently.

This is true, but does not change the fact that men and women can both want similar things in life, and that they can both achieve it through different ways of thinking!

>> They value different things in life

As you are a male, I don't think you are in a position to talk about what most (but never always) women want in life without providing citations.

>> Different choices have different outcomes. Then feminists come along and make the claim that the different outcomes are the result of a vast, evil conspiracy against women which pervades all of society

So

* Femminists clearly want different outcomes, and its not our place to tell them what outcomes they want, because we are not them.
  * Rationally, because [woman want different outcomes](https://www.pewresearch.org/fact-tank/2020/07/07/61-of-u-s-women-say-feminist-describes-them-well-many-see-feminism-as-empowering-polarizing/), it must mean there is some other blocker
    * And who else but men?
      * Its not quite a vast conspiracy, but certainly people like you rather than biology are the result of the outcomes - because clearly women have in mind what outcomes they want to achieve, otherwise feminism would not exist.

**Comment by TPS** [comment]
2 [Veritasium](https://youtube.com/c/veritasium) videos come to mind:
> I am inclined to trust

[The most common cognitive bias](
https://youtu.be/vKA4w2O61Xo)
> my research based hypothesis.

[Is most published research wrong?](https://youtu.be/42QuXLucH3Q)

**Comment by BenMcLean** [comment]
>  it is undeniably true that our culture paints men as less emotional.

First of all, there is no "our" culture. There's your left wing culture and my right wing culture and little to no overlap. We barely even speak the same language and generally fail to actually communicate effectively even when using the same words.

Second, everything is deniable.

Third, beyond the factual question of whether any given culture does this or not, there is also the moral question of whether doing so would be right or wrong.

On citing sources: you asked a question and I gave an answer. I didn't say the exclusively leftist academic and political establishment supported my answer. If you want the leftist narrative on anything, just use Google and Wikipedia. You don't even have to ask actual people: the party line is spelled out for you reliably every time. Now if you can follow my reasoning for even a moment, reflect on the fact that we all have Google and Wikipedia. We generally know what the establishment says is true. Belief in a proposition doesn't necessarily follow from the fact that there are studies to support that proposition. So when someone asks what ***I*** think,  I don't assume they're asking me to Google the question for them.

Even if we didn't have the problem of a very one-sided leftist political establishment controlling the credentialing process for public expertise making all public experts suspect for groupthink, there would still be the additional problem of the scope of scientific investigation. I don't believe you can take the methods which show us the strength of metals or the gravitational forces directing the course of comets and then apply these exact same methods directly to questions about human emotions and get answers which are just as objective and reliable. So-called experts who say you can are trying to sell something.

> Femminists clearly want different outcomes

No they don't. Like with all professional political activists, any actual solution to the problem on which their activism is based would put them out of a job so they don't actually want it.

**Comment by KittenHero** [comment]
I dont know why y'all are arguing when clearly neither side is willing to change thier mind

**Comment by TPS** [comment]
Feeding a troll is a standard pastime online, right?

**Comment by boehs** [comment]
> 2 [Veritasium](https://youtube.com/c/veritasium) videos come to mind:
> 
> > I am inclined to trust
> 
> [The most common cognitive bias](https://youtu.be/vKA4w2O61Xo)
> 
> > my research based hypothesis.
> 
> [Is most published research wrong?](https://youtu.be/42QuXLucH3Q)

You still did not provide any disproof for my claims

**Comment by boehs** [comment]
> Third, beyond the factual question of whether any given culture does this or not, there is also the moral question of whether doing so would be right or wrong.

The wonderful thing is morals change as we learn more

> On citing sources: you asked a question and I gave an answer. I didn't say the exclusively leftist academic and political establishment supported my answer. If you want the leftist narrative on anything, just use Google and Wikipedia. 

I did not link anything left wing or right wing, only studies.

> I don't believe you can take the methods which show us the strength of metals or the gravitational forces directing the course of comets and then apply these exact same methods directly to questions about human emotions and get answers which are just as objective and reliable. So-called experts who say you can are trying to sell something.

I don't think you understand anything about biology nor cognitive psychology. The linked research clearly outlines their methods of gathering information, and I think you will find it does not have much math equations if you spend the 5 minutes to skim any one.

Edit: And it's certainly better than the experience of one person (me or you) or news

> > Femminists clearly want different outcomes
> 
> No they don't. Like with all professional political activists, any actual solution to the problem on which their activism is based would put them out of a job so they don't actually want it.

Your job loss idea is silly, especially considering **[over 60%](https://www.wsj.com/articles/college-university-fall-higher-education-men-women-enrollment-admissions-back-to-school-11630948233) of college admissions are women**. The feminism movement is an equality movement, and I don't see how that means job loss.

Also, I keep circling back to this but as much as you wish, its not *your* place as a person unrelated in every way to feminism to decide what feminist's want. Even *if* anything you said was cited and potentially grounded in truth (and I am open to research/analysis that proves your claims), lets remember that people can want anything, regardless of if *you* think its good for them.

**Comment by BenMcLean** [comment]
> The wonderful thing is morals change as we learn more

No, they don't. Also, there's no "we." There's just you.

> I did not link anything left wing or right wing, only studies.

You linked exclusively left wing studies from exclusively left wing academia. The academic establishment and scientific community of the present time are collectively not credible. Every single one of these bastards say on their college admission forms that they "want to change the world," not discover the truth. They don't distinguish between science and activism.

I'm not even saying the results they report are necessarily faked. If they get results incompatible with the leftist political narrative, then they just change the question until they can be sure to get results that support it. Otherwise, they lose their position. Questions which would undermine the narrative are not asked (not made the basis for studies) because of course researchers want to keep their jobs and prestige and fit in. On the rare occasions that narrative-challenging work does get published, there aren't any Gestapo to break down their door yet, but they just quietly don't get research grants the next year and all of a sudden the [replication crisis](https://en.wikipedia.org/wiki/Replication_crisis) matters in the specific case of their study but not in all the other non-repeatable studies. The entire system is not credible. "Science" is whatever research you fund. It can support anything.

> I don't think you understand anything about biology nor cognitive psychology.

No, understanding does not entail belief and lack of belief does not entail misunderstanding.

> Your job loss idea is silly, especially considering over 60% of college admissions are women.

What do women have to do with feminists?

> The feminism movement is an equality movement

No, the feminism movement is brain cancer.

> Also, I keep circling back to this but as much as you wish, its not your place as a person unrelated in every way to feminism to decide what feminist's want.

This is a general problem with how incentives work for professional political activists. Political activists always claim that there is some crisis which necessitates funding their activism. If the crisis was gone then their activism would be unnecessary and would cease to receive funding, there being no crisis for their activism to solve. Thus, there is a built-in incentive in the very nature of political activism to never actually solve the crisis on which the activism is based so that the funding for the activism will continue.

Also, the same problem affects researchers. There is a built-in incentive for researchers to find that their field of study concerns a crisis which requires funding more research. Any researchers who say there isn't a crisis are then seen by their colleagues as traitors to their whole field, because their view makes it less likely their field will get increased funding. So the system selects for alarmist researchers over non-alarmist. We saw this happening with climatology twenty years ago and at the moment, it's happening with epidemiology.

**Comment by boehs** [comment]
> No, they don't

Lets see some definition inline with that claim, every resource I found in searching complements my claim.

> You linked exclusively left wing studies from exclusively left wing academia.

You have still linked absolutely nothing, let alone peer reviewed academia, despite encouragements from me previously to do so.

> No, understanding does not entail belief and lack of belief does not entail misunderstanding.

Fair enough, and yet you draw a false equivalence between two fields related only in name. The principles applied to rocket science are not applied to cognitive psychology

> What do women have to do with feminists?

Because [61% of women self describe themselves as feminists](https://www.pewresearch.org/fact-tank/2020/07/07/61-of-u-s-women-say-feminist-describes-them-well-many-see-feminism-as-empowering-polarizing/). The fact women are getting into college at a higher rate than men is surely an indicator of their ability to work in important fields (And even if you chalked it up to colleges trying to be woke, the fact remains that more women than men with degrees will lead to more women than men in the workforce)

> No, the feminism movement is brain cancer.

You have previously acknowledged that the movement is fighting for equality, but that you personally did not want equality. If you recall, that was what started my squabble with you. 

> This is a general problem with how incentives work for professional political activists. Political activists always claim that there is some crisis which necessitates their activism. If the crisis was gone then their activism would be unnecessary, there being no crisis for their activism to solve. Thus, there is a built-in incentive in the very nature of political activism to never actually solve the crisis on which the activism is based.

Lets equivalate this to a similar rights movement, the black rights movements in the 1900s. They were lead by people in similar political activism positions as what you describe, and yet from my perspective it was effective in obtaining what they set out to get. Do you think the civil rights movement was important? Do you think it was even slightly effective in giving black Americans rights?

**Comment by BenMcLean** [comment]
> Lets see some definition inline with that claim, every resource I found in searching complements my claim.

In the Great Books of the Western World, "morals" and "ethics" are used interchangeably to refer to that behavior a person has an obligation to enact or avoid.

> You have still linked absolutely nothing, let alone peer reviewed academia, despite encouragements from me previously to do so.

See my argument above on the fundamental lack of credibility in the university system.

> Fair enough, and yet you draw a false equivalence between two fields related only in name. The principles applied to rocket science are not applied to cognitive psychology

Your dogmatic assumption that human emotional problems can be addressed by studies and peer review is an attempt to apply the same principles from the hard sciences to the humanities. The medievals considered theology a science and theirs is the only sense in which psychology is a science.

> Because 61% of women self describe themselves as feminists.

I assume you mean in the United States or in Western countries? In which case, [in your same study it also describes 40% of men](https://www.pewresearch.org/fact-tank/2020/07/07/61-of-u-s-women-say-feminist-describes-them-well-many-see-feminism-as-empowering-polarizing/). So this doesn't really show "feminist" necessarily equals "woman" or vice versa.

> The fact women are getting into college at a higher rate than men is surely an indicator of their ability to work in important fields

I don't believe we share a common premise on what should count as important.

> You have previously acknowledged that the movement is fighting for equality,

Did I? That was a mistake. Only meant to acknowledge the fact that self-described feminists say they advocate for equality. In reality, self-described feminists actually engage in political activism for the advantage of leftist people over non-leftist. I can't say "women" here since different feminists disagree about the definition of a woman. They say they support "equality" but it isn't real equality since they've tipped the scales by interpreting all of history as oppression and then arguing that collective restitution should be made for this universal history of collective universal oppression in the individual persons currently living. That isn't real equality. Also, this restitution is only for leftist political coalition members. For instance, nobody advocates paying back the Mormons for losing all their property in their 1838 expulsion from Missouri because and only because they aren't a leftist political coalition member. So it isn't even the historically oppressed and marginalized: it's just leftists.

Oh and by the way, I'm not even saying the historical oppression is all fake. They'll use real historical oppression where they find it. They just don't stop with real historical oppression. They interpret ***all*** of history as oppression and this is not the case in real history.

> but that you personally did not want equality.

Yeah: real equality would entail a callous disregard for the needs of women and children together with a misguided attempt to change men to be more like women. Some are doing that but it is more common to find organizations like "Girls Who Code" which produce resources only for girls. (and for transgender maybe -- I honestly don't know which side of the alleged "gender gap" that organization counts which transgender people as being on)

Obviously, initiatives like, "Girls Who Code" are not for equality. Equality was what we had before: where the people determined to get into the field generally did so without the aid of such organizations. Girls were not oppressed under these conditions. Then along comes "Girls Who Code" to add that a special advantage will be created only for girls which boys never got and still won't get. Whether that is good or bad, it certainly isn't equality.

> Lets equivalate this to a similar rights movement, the black rights movements in the 1900s.

That is an excellent example of the principle.

> They were lead by people in similar political activism positions as what you describe, and yet from my perspective it was effective in obtaining what they set out to get.

Black activists today say it wasn't. They even say it's racist to claim that it ever was.

Of course, if people believed that past activism was effective to solve the problem then they'd see the problem as (at least somewhat) solved and that would make current activism seem less necessary, so (at least some) of its funding would more likely go towards other causes that are seen as more necessary, so there is a financial incentive to say that past activism didn't solve the problem whether it did or not. There's always a constant scramble, especially among left wing activists, to make one's own cause seem the most important.

By the way, this problem with reversed incentives for activism is also present for right wing political activists too, not just left wing ones.

Also, even posting on here, especially on a politically motivated parody repo like this, is putting my account in serious jeopardy of being banned for wrongthink. So I may just quit responding if I think you're trying to bait me into saying something that you can click "Report" on to get me banned. In fact, anyone even talking to you at all about any of this is taking a real personal, reputational and professional risk. Because your ideology is the one in power and privilege and ours isn't.

**Comment by activedecay** [comment]
This politically motivated parody repository will continue to foster a culture of serious business. We smash the patriarchy here no questions asked. No questions ever. Ben why are you not smashing the patriarchy?
